###############################################################################
###  File yml : Contain some global information for the project ###
###############################################################################


DEBUG : True
SECRET_KEY : '_5#y2L"F4Q8z\n\xec]/'


GOOGLE:
  URL: "https://maps.googleapis.com/maps/api/geocode/json"
  API_KEY: ""
  

MEDIA_WIKI:
  URL: "https://fr.wikipedia.org/w/api.php"
